### ISSUE TITLE
insert data with single quote attribute

### ISSUE THREAD

**Issue by chienjchienj** [j256/ormlite-core#102]
I got this exception when insert the object to database

### org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "tween": syntax error)

this object has a attribute value ==>  'tween

Any suggestion?

**Comment by j256** [comment]
Are you generating your own SQL?  You will need to use `?` SQL arguments and inject the 'tween string as an argument because some databases use single quote to escape strings.
