### ISSUE TITLE
(Lazy)ForeignCollections always calls dao.create() when calling add(T data)

### ISSUE THREAD

**Issue by HaukeRa** [j256/ormlite-core#104]
The documentation states:
```
/**
 * Add an element to the collection. This will also add the item to the associated database table.
 * 
 * @return Returns true if the item did not already exist in the collection otherwise false.
 */	
@Override
public boolean add(T data) {...}
```
In BaseForeignCollection.java

While working with this class I noticed that this does not hold true at least for LazyForeignCollections.
The  `T data` is always created in the database, even if it already exists.

BaseForeignCollection will always return true. LazyForeignCollection does not privide a specialized implementation. EagerForeignCollection has a specialized implementation, but relies on `List.add(..)`, which also always returns true.

Expected behaviour:
- Check if list contains element already (maybe utilizing another Collection than List, maybe Set), where the Collection would be considered not containing the element if it is not yet created
- Create element only when not alrady existing

**Comment by HaukeRa** [comment]
I just now saw that the base interface (ForeignCollection.java) states the current behaviour correctly:
```
/**
 * Adds the object to the collection. This will also add it to the database by calling through to [@link
 * {@link Dao#create(Object)}. If the object has already been created in the database then you just need to set the
 * foreign field on the object and call {@link Dao#update(Object)}. If you add it here the DAO will try to create it
 * in the database again which will most likely cause an error.
 * 
 * @see Collection#add(Object)
 */
```

But still I think the implementation could be changed to behave more predictable, that means calling createOrUpdate() after setting the parent to the data.

**Comment by j256** [comment]
Well certainly the `BaseForeignCollection` shouldn't have the invalid comment.  I've removed it.  In terms of calling `createOrUpdate()` versus `create()`, the issue is that `createOrUpdate()` only works if the entity being added has an ID which isn't always the case.

I think I want to keep the current behavior but do a much better job documenting.
