### ISSUE TITLE
Query on comma separated values

### ISSUE THREAD

**Issue by MustanserIqbal93** [j256/ormlite-core#105]
Hi,

I want to query on comma separated values from table how i can achieve this?

Values stored in Database are like  1,2,3

when querying from database i want to get those record where 2 exists.

Thanks.

**Comment by MustanserIqbal93** [comment]
I have found the option to get comma separated values. but the issue is i don't understand that do i need to pass array or i can pass any value to **(where.in)**. can you share an example. 

Thanks

**Comment by j256** [comment]
Sorry for the delay.  You can't use `IN` to search on a comma separated string.  You can use `LIKE` but you should make sure there is a comma at the start _and_ the end so you can do LIKE ',1,'.

**Comment by MustanserIqbal93** [comment]
Thank you so much for the reply. I have already solved it by using LIKE. Thanks once again.
