### ISSUE TITLE
Ormlite mysql PROCEDURE

### ISSUE THREAD

**Issue by passwhl** [j256/ormlite-core#109]
Ormlite mysql PROCEDURE

 String sql="{CALL sp_getstus('4f6496495df34cf592b5e90f7a340d11')}";
List<String[]> result=DBUtil.getDao(Stu.class).queryRaw(sql).getResults();

err:
 Could not perform raw query for {CALL sp_getstus('4f6496495df34cf592b5e90f7a340d11')}

**Comment by j256** [comment]
Is there any more details?  Please post the _full_ exception if possible.
