### ISSUE TITLE
Error in getFieldTypeByColumnName when using schema names in Sql Server

### ISSUE THREAD

**Issue by pmacn** [j256/ormlite-core#114]
Get the following error when trying to use a query builder on a table under a schema other than 'dbo'

`
java.lang.IllegalArgumentException: Unknown column name 'column1' in table schema1.table1
	at com.j256.ormlite.table.TableInfo.getFieldTypeByColumnName(TableInfo.java:155)
	at com.j256.ormlite.stmt.Where.findColumnFieldType(Where.java:649)
	at com.j256.ormlite.stmt.Where.between(Where.java:184)
        ...
`

I'm able to query the table without a query builder after using a variation of the solution suggested [here](https://groups.google.com/forum/#!searchin/ormlite-user/postgresql$20schema/ormlite-user/pjaK3o4-iLQ/1DmxcnL_apwJ)
But reading back the whole table isn't really feasible.

**Comment by pmacn** [comment]
So it turns out this was happening because I was trying to query using a column that I hadn't added to my POJO. Adding the column to the class resolved the issue.

I can keep the field on the class for now but would be interested to know if there's a solution for this scenario

**Comment by j256** [comment]
Sorry, I'm afraid I don't understand this.  ORMlite flagged the column as unknown because it was unknown.  What could it have done differently?

**Comment by pmacn** [comment]
At first I misunderstood some of the limitations of the code. I then realized it wouldn't let me filter on a column that wasn't in my POJO and corrected that. The initial title is misleading as it had nothing to do with the schema.

My follow-up question was simply to see if there was an interest in being able to filter on columns that aren't present in the object model. Since it already uses the column name directly to filter anyway.

**Comment by j256** [comment]
Still not sure I understand.  You can certainly put in raw parts of the WHERE portion of the query. 
 Does that help?  See: http://ormlite.com/javadoc/ormlite-core/com/j256/ormlite/stmt/Where.html#raw(java.lang.String,%20com.j256.ormlite.stmt.ArgumentHolder...)
