### ISSUE TITLE
Is there a way to persist foreign collections when the parent is saved?

### ISSUE THREAD

**Issue by barrychapman** [j256/ormlite-core#118]
I am writing a migration tool, and we select data from one DAO, and that selects the foreign records fine.

We want to then save it to another DAO. The parent record saves fine, but the child/foreign collections do not. What do we need to do?

**edit**

I guess a better way to state this would be, I want to select a record and foreign collections and replicate that on a different DAO. Is this possible? what is the best way to go about this?

**Comment by j256** [comment]
Sorry for the delay.  I'm sure you've moved on @barrychapman .  One way to do this is to use the `dao.getEmptyForeignCollection()` and assign it to the field in question.  Then when you add things to that collection they will be created in the database.  See:
https://ormlite.com/javadoc/ormlite-core/com/j256/ormlite/dao/Dao.html#getEmptyForeignCollection-java.lang.String-
