### ISSUE TITLE
How to make Generic Enum as OrmLite Column

### ISSUE THREAD

**Issue by sirbeastalot** [j256/ormlite-core#123]
I'm trying to minimize some of the work I'm going to have to do by "generifying" my lookup tables. They are all going to have `int id` as primary key but I'd also like them to have the ability to be searched by their "type" (whatever the Enum value is). Here's the abstract LookupRecord class

    public abstract class LookupRecord<T extends Enum<T>> extends DatabaseRecord {
        public static final String TYPE_FIELD_NAME = "type";

        @DatabaseField(unique = true, columnName = TYPE_FIELD_NAME)
        private T type;

        public LookupRecord(T type) {
            this.type = type;
        }

        public T getType() {
            return type;
        }
    }

So whenever I try to initialize the Dao for any of the lookup tables I get the following error:

`java.sql.SQLException: Field FieldType:name=type,class=LookupRecord improperly configured as type com.j256.ormlite.field.types.EnumStringType@5e80d5`

**Comment by j256** [comment]
Yeah this isn't going to work because of type erasure.  See: https://stackoverflow.com/a/47314641/179850
