### ISSUE TITLE
Is ThreadLocal the right way to handle transaction stack?

### ISSUE THREAD

**Issue by HaukeRa** [j256/ormlite-core#134]
After upgrading from ORMLite 5.0 to 5.1 i noticed deadlocks in the database (using Android so single connection)

After verifying that none of my code is deadlocking and after studying the changes in 5.1 i ask myself if 
`hreadLocal<TransactionLevel> transactionLevelThreadLocal`
in TransactionManager is to blame.

I only use Dao.callBatchTask which should synchronize on the DatabaseConnection on Android. But I call BatchTasks from different threads and also within another.

This worked perfectly on 5.0 but quickly fails on 5.1 (with the error that it was impossible to grant a connection to a thread while the database connection is listed as idle)

Wouldn't it be neccessary to manage the transaction stack for each database connection and not for each thread?

**Comment by j256** [comment]
Sh*t.  I tested this under Android but obviously not enough.

* Are you using the database from different threads _while_ you are running the batch operations?
* Once the batch finishes it's supposed to release the connection.  Is it not doing that?

**Comment by HaukeRa** [comment]
I need to dig deeper into the root cause or write a test case that provokes the error.

But the problem appears when I concurrently use the database from the UI thread and a background thread that serializes certain operations.

But I think a testcase is the way to go here.

**Comment by HaukeRa** [comment]
Made an example test project that produces the error. Note that its a flaky error so the test behaviou might differ from run to run.

https://github.com/HaukeRa/OrmliteTransactionTest

But what happens (expected failure) is that the test hangs. Either the background thread is blocked and the main thread waits for it to finish or the main thread is blocked, blocking the whole test.

**Comment by jjcampac** [comment]
I'm trying to upgrade my OrmLite version from 5.0 to 5.1 and I'm experiencing similar issues.
With the previous version the code below worked properly everytime was called. 

```
        List<Integer> result = new ArrayList<>();
        try {
            Dao dao = DBHelper.getHelper(context).getEmpDAO();
            QueryBuilder<Emp, Integer> queryBuilder = dao.queryBuilder();
            queryBuilder
                    .selectColumns(Emp.ID)
                    .where()
                    .ne(Emp.MODIFIED, Constants.DB_DELETED)
                    .prepare();
            GenericRawResults<String[]> grr = queryBuilder.queryRaw();

            for (String[] id : grr) {
                result.add(Integer.valueOf(id[0]));
            }
            grr.close();
        } catch (IOException | SQLException ex) {
            Crashlytics.logException(ex);
        }
```
However, with the new version, first time works fine, but next time I get the following messages:

```
08-08 10:54:10.501 15410-15485/org.svq.pol.gesate.movil W/SQLiteConnectionPool: The connection pool for database '/data/user/0/org.svq.pol.gesate.movil/databases/gesatedb.sqlite' has been unable to grant a connection to thread 601 (ModernAsyncTask #1) with flags 0x1 for 841.093 seconds.
    Connections: 0 active, 1 idle, 0 available.

08-08 10:54:20.740 15410-15558/org.svq.pol.gesate.movil W/SQLiteConnectionPool: The connection pool for database '/data/user/0/org.svq.pol.gesate.movil/databases/gesatedb.sqlite' has been unable to grant a connection to thread 656 (IntentService[Configuración Sync Service]) with flags 0x1 for 840.064 seconds.
    Connections: 0 active, 1 idle, 0 available.
```
In the last post from @j256 it's said there are some related problems fixed, but the only OrmLite version I find at Maven repositories is one published on February 2018, almost one year before the publication of the post.

**Comment by j256** [comment]
For the record, the 5.2 release just pushed out has some fixed to the `TransactionManager` which may resolve this issue.  Feedback welcome.   See: https://github.com/j256/ormlite-core/commit/74ceed2394fbe9555d9cb61a2c2c174140bd393e

**Comment by j256** [comment]
Feel free to reopen if you are still having issues.  Make some more tweaks to the `TransactionManager` that will be in 5.3.  See: https://github.com/j256/ormlite-core/commit/766b124e09c972c34f2cdce1cddde84aa7e013f8
