### ISSUE TITLE
NullPointerException during constructing exception message when field setter fails.

### ISSUE THREAD

**Issue by hrach** [j256/ormlite-core#135]
Currently, if db contains a null value and the property is defined with simple (non-nullable) type, the code may fail here:

https://github.com/j256/ormlite-core/blob/d20a65066d35284678b63eeaa3cb70688d678ef5/src/main/java/com/j256/ormlite/field/FieldType.java#L562

However, during the construction of error message here

https://github.com/j256/ormlite-core/blob/d20a65066d35284678b63eeaa3cb70688d678ef5/src/main/java/com/j256/ormlite/field/FieldType.java#L565

the code fails since the `val` is null -> `val.getClass()` cause `NullPointerException`. This is quite unfortunate, since from the final exception and stack trace it's impossible to say which field/property cause the exception.

**Comment by j256** [comment]
Yeah this is a bug.  Probably long standing.  Thanks for reporting it.  Fixed here: https://github.com/j256/ormlite-core/commit/1c2724ac02f87ef5be9bc7a8c93fcadd5a2abf93

**Comment by hrach** [comment]
Thank you, that was fast! :)

**Comment by j256** [comment]
Interestingly, when I went to the code, I'd already fixed it recently but it hadn't been checked in.  Not 100% sure when/how I discovered it.  My brain sometimes works poorly.  But your issue gave be good information for creating the unit test which was instrumental.  Thanks again.
