### ISSUE TITLE
Foreign Objects only get created not updated.

### ISSUE THREAD

**Issue by natschz** [j256/ormlite-core#137]
@j256 I'm creating a object which has foreign objects i save this parent with createOrUpdate().
This works fine the first time, but the second time i try to save i get a primary key violation for the child.

[This]( https://github.com/j256/ormlite-core/blob/58ea8995657ede3670caa8aaf004cd439e35b0e0/src/main/java/com/j256/ormlite/dao/BaseForeignCollection.java#L196) is where it happens, i don't understand why would the children always be created if for the parent createOrUpdate is called?

**Comment by j256** [comment]
Can you post a trimmed down unit test that shows the failure @natschz ?  Right now I don't fully understand the error.

**Comment by j256** [comment]
Going to close for now.
