### ISSUE TITLE
fullColumnDefinition parameter being ignored.

### ISSUE THREAD

**Issue by ethanmdavidson** [j256/ormlite-core#138]
I have a field with the DatabaseField annotation and the new fullColumnDefinition parameter, but it appears that the fullColumnDefinition parameter doesn't actually affect the CREATE TABLE statement that ormlite generates. 

```Kotlin
@DatabaseField(foreign=true, foreignAutoRefresh=true, fullColumnDefinition="MY_ACCOUNT_COLUMN NUMBER")
var account:M_ACCOUNT = M_ACCOUNT()
```
in the console:
```2018-03-29 11:22:52,445 [INFO] TableUtils executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS ... `account_id` INTEGER ...```

Same thing if I specify the columnName:
```Kotlin
@DatabaseField(foreign=true, foreignAutoRefresh=true, columnName="ACCOUNT" fullColumnDefinition="MY_ACCOUNT_COLUMN NUMBER")
var account:M_ACCOUNT = M_ACCOUNT()
```
in the console:
```2018-03-29 11:22:52,445 [INFO] TableUtils executed create table statement changed 0 rows: CREATE TABLE IF NOT EXISTS ... `ACCOUNT` INTEGER ...```

I am using Kotlin, but I don't think that should affect it. The columnDefinition parameter works as expected, but doesn't work for my purposes because I need to have ormlite use a certain column name when creating and a different column name when querying.

Also probably worth mentioning that there's a typo in the [Local Annotations section of the docs](http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_2.html#Local-Annotations) with foreignColumnName being listed twice.

**Comment by j256** [comment]
Any chance you need to update your database config file?  http://ormlite.com/docs/table-config

**Comment by ethanmdavidson** [comment]
No, I am not using one. 

It looks like its not being used anywhere in the project. Shouldn't it be using [in TableUtils like columnDefinition](https://github.com/j256/ormlite-core/blob/e41f83a5a5ec8aec42ea6f30630ae0a8130a7c8f/src/main/java/com/j256/ormlite/table/TableUtils.java#L505) is?

**Comment by j256** [comment]
Geez.  Ok.  I'm an idiot.  Not implemented fully and no tests on this of course.   Fixed with https://github.com/j256/ormlite-core/commit/4175cbcddde42b02c900079b0a6ded1ee0ef7f24
