### ISSUE TITLE
createOrUpdate and createIfNotExists is not process-safe

### ISSUE THREAD

**Issue by Mygod** [j256/ormlite-core#139]
I see #119 fixes a race condition in the same process but I need to use ormlite in two processes. Any chance of fixing this?

**Comment by j256** [comment]
Sorry but I'm not going to fix this in ORMLite.  I think it crosses the "lite" barrier and introduces a crap of per architecture support.

**Comment by Mygod** [comment]
Sounds reasonable. Thanks.
