### ISSUE TITLE
Get ResultSet directly

### ISSUE THREAD

**Issue by nonameplum** [j256/ormlite-core#14]
Hi,

I suggest to add queryRaw method that custom mapper can use ResultSet directly instead of Column and Values only.

Example:
```
dao.queryRaw("SELECT * FROM TABLE", new ResultSetMapper<Object>() {
            @Override
            public Object map(int index, ResultSet r, StatementContext ctx) {
                ...
            }
        });
```        

This is more open to developer.

**Comment by j256** [comment]
I've added the DatabaseResultsMapper which will be in 4.49.
