### ISSUE TITLE
ByteArrayType misbehaves for binary data

### ISSUE THREAD

**Issue by noordawod** [j256/ormlite-core#146]
When the system's default character set uses extended bytes (like Unicode), the following call will convert the original binary data wrongly by adding a variable number of bytes to it:

https://github.com/j256/ormlite-core/blob/20cf75e51467892a12c091a9213c493c1787922b/src/main/java/com/j256/ormlite/field/types/ByteArrayType.java#L66

Would it be possible to send a PR for adding a `BinaryType` which resembles this type, but specifically uses ASCII charset internally?

**Comment by noordawod** [comment]
Okay, this is unnecessary because I tracked down the bug to using a very old MySQL Connector/J driver. Using ByteArrayType worked as expected with the latest driver.

**Comment by noordawod** [comment]
After double-checking with a project I'm working on, it DOES seem like `getBytes()` is misbehaving when reading bytes from JDBC result. I did upgrade to the latest Connector/J driver but it didn't help.

I added support for setting a character set for `ByteArrayType` which fixed it in my case (I used `ISO-8859-1` as the format).

**Comment by j256** [comment]
Merged #148.
