### ISSUE TITLE
Support for SQL functions in Where() clauses

### ISSUE THREAD

**Issue by juur** [j256/ormlite-core#155]
It would be useful to be able to somehow pass SQL functions to the Where clause, for example:
`.where().eq("password", new AesEncryptFunction("salt"))`
This being translated into SQL:
`WHERE password = AES_ENCRYPT(password,"salt")`

Any thoughts on where this would best be implemented (probably by interface(s) to allow people to easily extend for different functions, maybe organised by driver)

My first thought was in `BaseComparision.appendArgOrValue` within another `instanceof` check then invoke? However I am not that familiar with the inner workings.

**Comment by juur** [comment]
Hmm. Actually thinking about this, if a field is set/get using `AES_ENCRYPT()` and `AES_DECRYPT()` then this won't work for the actual ORM functionality and would need some `@DatabaseField` magic also.

**Comment by j256** [comment]
Let's take a step back.  Is the goal to encrypt data?  This has been a missing feature for a while.  How would it work?  How about callbacks on the dao for every field store and retrieve?

**Comment by meydominic** [comment]
Hello,
what about adding the ESCAPE clause to Where() clauses?

`SELECT * FROM `access_domain` WHERE `domain` LIKE '\%.bla bla bla-%'  ESCAPE '\'`

**Comment by j256** [comment]
Sorry for the delay @meydominic .  That seems like another issue.  Also, I think you should look into [SQL argument support](https://ormlite.com/docs/select-arg).

**Comment by j256** [comment]
Sorry for the delay on this @juur .  Would the encrypt/decrypt have to work on all fields?  Or maybe could it just be for string fields?  Is a custom persister maybe enough with some wiring help?
