### ISSUE TITLE
Apostrophe causes SQLException

### ISSUE THREAD

**Issue by xeinebiu** [j256/ormlite-core#178]
name = Audio 'Level 2' Stories   

Dao
`
        fun get(
            context: Context,
            name: String
        ): AlbumEntity? =
            getInstance(context).albumsDao.queryBuilder()
                .where()
                .eq(AlbumEntity.COLUMN_NAME, name)
                .queryForFirst()
`

Exception
`
 java.sql.SQLException: Problems executing Android query: SELECT * FROM `albums_v2` WHERE `name` = 'Audio 'Level 2' Stories'  LIMIT 1
`

Version
`
   implementation group: 'com.j256.ormlite', name: 'ormlite-android', version: '5.1'
`

**Comment by xeinebiu** [comment]
Using "SelectArg(value)" seems to fix this issue.

**Comment by j256** [comment]
This is a FAQ: https://ormlite.com/docs/quotes-in-queries
