### ISSUE TITLE
Native query

### ISSUE THREAD

**Issue by Taliro** [j256/ormlite-core#201]
I everyone,

I need to execute native query but i don't find it.
I try pass class Map into daoManager like this : 

`DaoManager.createDao(Datasource.getEm(), Map.class)`

but ORMlite cry and say "No fields have a DatabaseField annotation in interface java.util.Map"

I haven't class for my query, i search to execute query into information_schema in my db postgres.

I searched everywhere but i can't found how do that.

someone can help me ?

**Comment by j256** [comment]
What are you trying to accomplish?  The [documentation on the QueryBuilder](http://ormlite.com/docs/query-builder) didn't help?

**Comment by Taliro** [comment]
Yes, but this example match with Entity class and i haven't this.

I need to execute "select 1 from information_schema where table_schema = 'schema_name' AND table_name = :tableName"

Return Map or boolean how i cant do that ?

**Comment by j256** [comment]
There is also [raw queries](https://ormlite.com/docs/raw-queries).  Have you looked through the documentation yourself?

**Comment by Taliro** [comment]
of course.

Documentation say : 

``` 
// find out how many orders account-id #10 has
GenericRawResults<String[]> rawResults =
  orderDao.queryRaw(
    "select count(*) from orders where account_id = 10");
// there should be 1 result
List<String[]> results = rawResults.getResults();
// the results array should have 1 value
String[] resultArray = results.get(0);
// this should print the number of orders that have this account-id
System.out.println("Account-id 10 has " + resultArray[0] + " orders");
```
`orderDao` reference to `DaoManager.createDao(Connection, Order.class)` right ? 

this is again an entity class, but **i don't** this

i need do that : 

```
DaoManager.createDao(connection, Map.class).queryRaw(myQuery).getFirstResult()

```

Problem : ORMLite throw an exception `No fields have a DatabaseField annotation in interface java.util.Map`

**Comment by Taliro** [comment]
Up ?

**Comment by j256** [comment]
By the word "up" are you asking if there are problems with the webserver?  There were.  Fixed.

**Comment by j256** [comment]
Whatever query you need to make should go here:

```
GenericRawResults<String[]> rawResults =
  orderDao.queryRaw(
    "select 1 from information_schema where table_schema = 'schema_name' AND table_name = ?", "table-name-arg");
```

You will need a DAO object for this.  ORMLite was designed to handle Java entities.  If you are just trying to get access to the `information_schema` then you might consider using a different tool.

I have no idea what you mean by trying to create a DAO for a Map object.  It needs to be an entity like `Order` in the examples.

**Comment by j256** [comment]
I just closed this but if there is any additional issues, feel free to reopen.
