### ISSUE TITLE
About Log

### ISSUE THREAD

**Issue by RamboMing** [j256/ormlite-core#203]
Hello,
I want to disable log，
I use System.setProperty(LocalLog.LOCAL_LOG_LEVEL_PROPERTY, "ERROR")，
But It doesn't work !
What should I do?

**Comment by j256** [comment]
According to the [docs about logging](https://ormlite.com/docs/logging) it says the following:

> For all of the logging implementations, you can use the Logger.setGlobalLogLevel(...) method to filter all log messages. The argument you pass in filters out any messages to less important levels. You should call that method in the main(...) method or as early in your application as possible.

>     // only allow error or fatal messages
>     Logger.setGlobalLogLevel(Level.ERROR);

Did you try that?

**Comment by RamboMing** [comment]
sorry,I not find the method in version 5.1

**Comment by RamboMing** [comment]
Thinks! maybe i can use ASM.
