### ISSUE TITLE
[Question][foreign] Help with connections.

### ISSUE THREAD

**Issue by JavLock** [j256/ormlite-core#217]
The idea is this:
The program receives a file (PdfFile), parses it, saves it to the database
Saves data (SieveTag) received during parsing

I need to get all SieveTags when requesting a PdfFile
I need to get all PdfFile when requesting SieveTag
1:
![1](https://user-images.githubusercontent.com/87483305/127747789-f8d26e55-d4f2-4d75-98ab-37cd8e651f97.png)
2:
![2](https://user-images.githubusercontent.com/87483305/127747816-fccc5f84-5b38-4de5-acbc-52f796961ce2.png)
3:
![Screenshot_20210731_172029](https://user-images.githubusercontent.com/87483305/127747765-33c93629-1aed-448a-bbdb-d09c3f19666a.png)

**Comment by j256** [comment]
Sorry but I can't really help with this.  If you want to ask a specific ORMLite question with some ORMLite code then I may be able to help.

**Comment by JavLock** [comment]
I used to write such a code, the connection was through the 3rd table

**Comment by JavLock** [comment]
used https://ormlite.com/javadoc/ormlite-core/doc-files/ormlite.html#Foreign-Collection

**Comment by j256** [comment]
Best of luck @JavLock getting back into the code.  The documentation might help: https://ormlite.com/javadoc/ormlite-core/doc-files/ormlite.html#Getting-Started
