### ISSUE TITLE
Make default for isArgumentHolderRequired configurable ?

### ISSUE THREAD

**Issue by hofmandl1** [j256/ormlite-core#219]
Sorry if this is more a question than an issue, however I am concerned about the QueryBuilder feature increasing the likelines of creating code susceptible to SQL injections.

We recently had code like this:
```
@DatabaseTable(tableName = "myTable")
public class TableRow {
    public static final @NonNull String ID_COLUMN = "ID";
    public static final @NonNull String NAME_COLUMN = "Name";

    @DatabaseField(columnName = ID_COLUMN, generatedId = true, canBeNull = false)
    private int dbId;

    @DatabaseField(columnName = NAME_COLUMN, canBeNull = false)
    private String name;
}
...
       final DeleteBuilder<TableRow, Integer> delete = dao.deleteBuilder();
       delete.where().eq(TableRow.NAME_COLUMN, "'"); // the string is a name for a thing and can be user-supplied
       dao.delete(delete.prepare());
```
which crashed with an "illegal SQL" Exception instead of simply deleting that row (or doing nothing if no such row exists).

To our surprise we found out, that the querybuilder doesn't use an Argument-Placeholder (?) for building the sql-query-string but rather a simplistic quoting. When investigating this further we found our user-error, of not specifying the database-fieldtype with a persister that overrides the default of

```
	@Override
	public boolean isArgumentHolderRequired() {
		return false;
	}
```

to `true`.

We also found out, that this method is only used by the queryBuilder but not by queries created by calls to `create(Entity)` or `delete(Entity)`.

So we kept wondering, why this difference and how we should ensure that for all our future column definitions where potentially user-supplied strings can make it into a query-Builder argument will have `isArgumentHolderRequired` properly configured.

We then found about `DataPersisterManager.registerDataPersisters` that allows to register custom persister implementations globally that can apply for all fields of e.g. type `String` that do not have a specific Persiste class registered. However that still wouldn't ensure, that nobody can introduce a new field type that is somehow serialized to a string when inserting it to the database. This of course may not be very likely.

Anyway here comes the question: Would it be possible, to always use ArgumentPlaceHolders ? Or would it be possible to e.g. allow for setting a java property that would make QueryBuilder-instances ignore the return value of `isArgumentHolderRequired` and simply assume it had returned `true` all the time ?

**Comment by j256** [comment]
No it has nothing to do with the `isArgumentHolderRequired` database setting.  If you do a query in the documentation for query arguments you would have seen the docs on this subject: https://ormlite.com/docs/select-arg

To quote: Select Arguments are arguments that are used in WHERE operations can be specified directly as value arguments (as in the above examples) or as a SelectArg object. SelectArgs are used to set the value of an argument at a later time – they generate a SQL ’?’.

In your case:

       SelectArg selectArg = new SelectArg();
       delete.where().eq(TableRow.NAME_COLUMN, selectArg); // the string is a name for a thing and can be user-supplied
       selectArg.setValue("some user input");
