### ISSUE TITLE
Connection leak when working with ForeignCollectionField using Stream API

### ISSUE THREAD

**Issue by zhemaituk** [j256/ormlite-core#230]
Given a class:

```
public class Transaction {
    ...

    @ForeignCollectionField(foreignFieldName = "transaction")
    private Collection<Document> documents;
}
```

And then working with it using Stream API leaves the acquired connections behind. Happens in number of ways, but simple way to reproduce is:

```
Transaction transaction = dao.queryForId(id);
Document document = transaction.getDocuments().stream().findFirst().get();

final int numberOfConnections = 3;

// 1 connection for dao.queryForId. And 2! more created during java.util.Spliterators.IteratorSpliterator#estimateSize
verify(connectionSource, times(numberOfConnections)).getReadOnlyConnection(any());

// Expecting that all connections where released, but actually one connection was not (one of the connections acquired during IteratorSpliterator#estimateSize remains acquired)
verify(connectionSource, times(numberOfConnections)).releaseConnection(any());
```

Reproduced with ormlite 5.6

**Comment by zhemaituk** [comment]
The code examples above do not compile, still after fixing compilation and running - one connection remains not released. Stream.close does pretty much nothing, it does not close any iterators (java.util.Iterator is not Closeable, no surprise here).

I think if you want to keep current design in place, ForeignCollection.stream()/.spliterator()/.parallelStream() methods need to be overridden, as the standard StreamSupport implementation does not close any underlying iterators, and generally is not efficient for the purpose (e.g. calls both size() and iterator()).

To be honest even multiple queries to database were a surprise. 
Initializing the collection only once when getDocuments() is called on the persisted object for the first time would be more intuitive.

Consider this as a feedback as we had to switch to use Dao for all such operations, as otherwise it is too easy to shoot own foot with performance hit or connection leak.

**Comment by j256** [comment]
I was hoping that you could figure it out.  It was somewhat off the top of my head since my stream experience is pretty minimal and it had a bunch of problems.

I've updated the example that seems to work for me.  At least I see the iterator being closed.

**Comment by j256** [comment]
Interesting to compare these 2 stream lines:

	// missing the try / catch
	documents.stream().onClose(() -> documents.closeLastIterator()).findFirst().get();

This creates 2 iterators for some reason.  They both are closed.  However this code:

	CloseableWrappedIterable<Document> iterable = transaction.getDocuments().getWrappedIterable();
	Document document = StreamSupport.stream(iterable.spliterator(), false)
		.onClose(() -> IOUtils.closeQuietly(iterable)).findFirst().get();

This only creates 1 iterator which is closed.

**Comment by zhemaituk** [comment]
The first example provided acquires 2 connections to the database, but releases only 1 of them.
It does create 2 iterators, and indeed calls close 2 times, but both times on the same iterator object, so only one iterator gets closed.

The second example provided opens 1 connections to the database, but closes none of them (in case there are at least 2 elements in the collection).


The problem is that the `java.util.Collection#stream` method is not overridden in `LazyForeignCollection`. So the default implementation is used from`java.util.Collection`, which does not do anything on `java.util.stream.BaseStream#close`.
If a Stream has underlying IO resources it should override `java.util.stream.BaseStream#close` method. For example similar is done in `java.nio.file.Files#lines(java.nio.file.Path, java.nio.charset.Charset)`.

It makes sense to override `java.util.Collection#spliterator` method in `LazyForeignCollection` as well, as the default implementation has `java.util.Spliterator#SIZED` characteristic which is not suitable for the lazy collection backed by DB connection.

Overriding both methods in this way will make such call `documents.stream().findFirst().get();` creating exactly one iterator and releasing resources automatically as terminal operation of the stream has been reached.

**Comment by j256** [comment]
Ok.  I deleted my 2 last posts.  They were somewhat broken.  I've also removed the `closeLastIterator()` usage because if there are 2 connections opened, only the last one is freed.  That makes sense.  Sorry for my ignorance on this subject.

However I push back on the idea that Streams has some auto-close mechanism for terminal methods.  I'd like you find me an example of that.  You mentioned `java.nio.file.Files#lines(...)` which does not do that.  If you look at this [SO answer](https://stackoverflow.com/a/27382060/179850) you can see how you have to close it yourself.  The following code does not spit out "Closed" at the end.

	Stream<String> stream = Files.lines(Paths.get("/tmp/x")).onClose(() -> System.out.println("Closed"));
	stream.forEach(System.out::println);

Here's one answer why [terminal methods don't auto-call close](https://stackoverflow.com/a/28814024/179850).  It would be nice to add a `closeOnTerminal(true)` method to `Stream`.  I think that's an oversight.

**Comment by zhemaituk** [comment]
Yes, you right, terminal methods do not call close automatically, I misread javadoc. For sure responsibility of the developer to close such streams.

**Comment by j256** [comment]
Wow, no "thanks for your help" or "sorry to waste your time on this".

**Comment by zhemaituk** [comment]
Pardon, but there were no help.
The issue still exists.
Even if developer closes the stream explicitly - connections are not released.

Such code still acquires 2 connections and releases only 1:
```
try (final Stream<Document> stream = transaction.getDocuments().stream()) {
    stream.findFirst().get();
}
```

`LazyForeignCollection#stream()` is not overridden, so default implementation is used, which does nothing on close().

Neither `LazyForeignCollection#spliterator()` is overridden, so default implementation with java.util.Spliterator#SIZED characteristic is returned which indicates that size() operation is almost free.

Please treat this ticket as a feedback and not ask for help. It is not that complex to avoid using streams when you know about the connection leak possibility, but I am pretty sure you care about quality of your library and that other users do not encounter the same.

**Comment by j256** [comment]
No help?  So you didn't learn anything.  Strange.  But you've got a good point about `stream()` still not closing.  The question is how to fix it while not requiring Java 8....

**Comment by zhemaituk** [comment]
Java 6 reached end of support in 2018 ( https://support.oracle.com/knowledge/Middleware/2244851_1.html ).
Again, treat this ticket as a product feedback, not ask for help, I addressed connection leak for my project before creating this ticket.

**Comment by j256** [comment]
For the record, I know java 6 was end-of-life a ways back but I try to not move to newer versions unless I have to or there are compelling reasons.  I'm in the process of moving to java 7 right now for AutoCloseable mostly.  Java 8 maybe in a year or 3.  :-)
