### ISSUE TITLE
test that relies on field-order in testComboIndex

### ISSUE THREAD

**Issue by CharlesZKQ** [j256/ormlite-core#238]
The com.j256.ormlite.table.TableUtilsTest.testComboIndex is a flaky test, which is the same reason for [#222](https://github.com/j256/ormlite-core/pull/222). Based on you feedback, I think you may prefer to fix this flaky this flaky test in your own way, so I open an issue instead of PR for this flaky test. 
The way to reproduce the flakiness is to use [NonDex](https://github.com/TestingResearchIllinois/NonDex). All detail steps have been illustrated in readme. Follow the steps you could reproduce flakiness of this test

**Comment by j256** [comment]
Thanks much @CharlesZKQ .  I didn't know about NonDex.  It showed a couple more tests that relied on field order.  I've got some outstanding work and then I will fix this.
