### ISSUE TITLE
Exception raised on non-foreign field about maxForeignAutoRefreshLevel and foreignAutoRefresh

### ISSUE THREAD

**Issue by efung** [j256/ormlite-core#26]
I'm using a build of ormlite-core from master (commit e653256eefe6ada8bf6a8fe9b52a5d85ac549142) on Android.

I'm getting this runtime exception when creating a table:

    java.lang.IllegalArgumentException: Field address1 has maxForeignAutoRefreshLevel set (2) but not foreignAutoRefresh is false
            at com.j256.ormlite.field.FieldType.<init>(FieldType.java:273)
            at com.j256.ormlite.table.DatabaseTableConfig.convertFieldConfigs(DatabaseTableConfig.java:249)
            at com.j256.ormlite.table.DatabaseTableConfig.extractFieldTypes(DatabaseTableConfig.java:116)

The relevant field has this definition:

	@DatabaseField
	private String address1;

In 4b3a3dda9d07c83c7afa4519f3eb2e642ededbd7 , you changed how the default recursion level is injected. Does this now change the level for all fields? Should there be a check that the field is actually a foreign one?

This problem never occurred for me when using ormlite-core 4.4.8 . I don't ever set the refresh level in my models.

**Comment by jkwuc89** [comment]
I ran into this issue as well when I cloned/built the git repos for ormlite-core and ormlite-android and included the resultant jars inside my Android mobile app project. My Android device is running Android 4.2.2 - API 17. There appear to be a few workarounds for this. Which one has worked best?

**Comment by efung** [comment]
@jkwuc89 If you're able to edit the source and build the JAR yourself, you could just remove the line that raises the exception, i.e.

https://github.com/j256/ormlite-core/blob/64b854e52ddd28435226956fe8de5a17a802a599/src/main/java/com/j256/ormlite/field/FieldType.java#L273

**Comment by konmik** [comment]
I would advise against commenting out the exception line. You're not fixing the cause of the problem - some data is still uninitialized. The proper way to handle this is to turn off the legacy code: https://github.com/j256/ormlite-core/issues/26#issuecomment-57532056

**Comment by j256** [comment]
Sorry to be so silent on all this.  Any consensus?  So this seems to be occurring because of the hacks trying to get the annotations to perform better?

**Comment by konmik** [comment]
@j256 Yes, I think so. I would just remove that hack.

**Comment by j256** [comment]
Uh, that's not going to happen.  It gives an order of magnitude speed improvement to annotation processing.  How about the ability to disable it programmatically?  Leave it on by default but maybe set a system property or something to disable it?  How about that?

**Comment by j256** [comment]
See my SO question here if you have any questions: http://stackoverflow.com/questions/7417426/why-are-annotations-under-android-such-a-performance-issue-slow

**Comment by konmik** [comment]
@j256 I understand that annotations processing was slow on android on pre-honeycomb devices. But this workaround only works for some little percent of devices that has apache annotations processing library installed. I personally do not develop for minSdk < 15, but if you will fix it then I can test it.

**Comment by jkwuc89** [comment]
To workaround the IllegalArgumentException described above when I run my app on a Samsung Galaxy tablet running Android 4.2.2, I tried the following two workarounds and both work with an equal level of performance.

In ormlite-core: Comment out the throw new IllegalArgumentException inside FieldType.java at line 273.
In ormlite-android: Change private static final int[] configFieldNums = lookupClasses(); to private static final int[] configFieldNums = null; inside DatabaseTableConfigUtil.java at line 38.

My question is this. Which of these workarounds is safer?

**Comment by j256** [comment]
I think the setting to null sounds safer to me.  It should also be faster.

**Comment by j256** [comment]
Ok.  I [finally] understand this.  It's a bug for sure.  I've added this bug issue: https://sourceforge.net/p/ormlite/bugs/194/

To fix this I've removed the sanity check in FieldType.  I've also added support for a `ormlite.annotation.hack.disable` system property to disable the annotation hacks: 

	if (android.os.Build.VERSION.SDK_INT < android.os.Build.VERSION_CODES.ICE_CREAM_SANDWICH
			&& System.getProperty(DISABLE_ANNOTATION_HACK_SYSTEM_PROPERTY) == null) {
		configFieldNums = lookupClasses();
	} else {
		configFieldNums = null;
	}

**Comment by j256** [comment]
I just found the actual root of the problem in ormlite-core.  It happens when you programmatically configure the max-auto-refresh to be the default (like with Android annotations).  This would turn on auto-refresh.  I added test coverage (finally) for this and fixed in trunk.  Will be in 4.49.  See: https://github.com/j256/ormlite-core/commit/c7eca0bc9ca9cece47e2b41bb27b615fdc01952c
