### ISSUE TITLE
TableUtils.createTableIfNotExists still tries to create id sequence even if table exists

### ISSUE THREAD

**Issue by netoneko** [j256/ormlite-core#36]
How to reproduce:

```java
@DatabaseTable(tableName = "comments")
public class Comment {
    @DatabaseField(generatedId = true, allowGeneratedIdInsert=true)
    public Integer id;

    @DatabaseField(canBeNull = false)
    public String text;
}
```

Then run `TableUtils.createTableIfNotExists(connectionSource, Comment.class)` twice.

**Comment by j256** [comment]
Yes this is a dup of #20 .

**Comment by otaviofff** [comment]
Both issues #36 and #20 have been closed without a solution.

I understand they are duplicates, but none of them found a solution to the issue in question.

 if you run twice `TableUtils.createTableIfNotExists(connectionSource, Comment.class)`, on PostgreSQL, you get an exception `java.sql.SQLException: SQL statement failed: CREATE SEQUENCE` 

BTW, this doesn't happen on MySQL. 

Can you please check? Thanks a lot!
