### ISSUE TITLE
Observer change notification not received when calling deleteById

### ISSUE THREAD

**Issue by DanielJette** [j256/ormlite-core#37]
It appears that `StatementExecutor.deleteById` was missed when adding support for the DaoObserver pattern for Android in https://github.com/j256/ormlite-core/commit/e653256eefe6ada8bf6a8fe9b52a5d85ac549142

Seems `dao.notifyChanges()` needs to be called.

**Comment by j256** [comment]
Thanks for this.  Created this bug: https://sourceforge.net/p/ormlite/bugs/190/

**Comment by j256** [comment]
Here's the check-in.  Thanks.  https://github.com/j256/ormlite-core/commit/33b1b28b3312c6e86007b3e3f041e175f1273618
