### ISSUE TITLE
Wrong behavior of the lazy collection iterator.

### ISSUE THREAD

**Issue by igromanru** [j256/ormlite-core#4]
This test (a885740148c30436ff6fc27e11b6a114c0b2bf2b) tests the state of the iterator after delete. It works as it should only with eager collection iterator.  We have an object with collection of 3 depended objects. We get the collection's iterator and move to the first, then to the second element, delete the second element and move to the next element and back. After that we read the current object.

With eager collection this is the first element, because the iterator is coherent with the underlying list. Right now we can't test the lazy collection iterator because the underlying cursor can't move backwards, see another ticket. But it works on the Android and this test fails there. The element we get there at the end is deleted second one. This is because the delete of the lazy collection iterator goes direct to the DB and the collection and iterator itself don't get know that something has been changed.

So we need a way to get the iterator informed, so he can react on the delete and get the new state or skip the deleted elements. Or iterator should delete the element itself. For the second scenario the bitmap can be used for storing the mask of deleted elements, but this isn't a very good solution, maybe there are better ones.

**Comment by GitHubMurt** [comment]
I hope I have the same issue
I have 

```
class Project{
....
         @ForeignCollectionField(eager = true)
          private Collection<Attribute> workerGroupsAttributesDB = new    ArrayList<>();
....
}
```
and while I do 

```
iter = projectHashMap.get(openedProject.getIdDB())
                .AttributesDB().iterator();
        while (iter.hasNext()){
            if(iter.next().getIdDB() == wpa.getIdDB()){
                iter.remove();
            }
        }
```

whan program reached  _item.remove()_ it throws exception that attempt to re-open already closed db.... althouth I my collection is eager - look i can read _iter.next.getIdDB_ . Why my collection is so strongly connected to DB? I just want to remove this object. It's all.
