### ISSUE TITLE
Cannot count selected distinct columns

### ISSUE THREAD

**Issue by spacetime** [j256/ormlite-core#42]
We had a case where we needed ORMLite to execute a query similar to
```
SELECT COUNT(DISTINCT "Field5") FROM Table1 WHERE conditions...
```
If we look at
https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/stmt/QueryBuilder.java#L466
it shows, on using .countOf(), ORMLite ignores the selected field and only has COUNT(*) instead.

**Comment by j256** [comment]
Thanks for this.  This feature has been added.  See: https://github.com/j256/ormlite-core/commit/2c6d3173971dd69519a43c4d53b220fdf2203878

**Comment by spacetime** [comment]
Thanks for the fix! I owe you a patch now! :smile:
