### ISSUE TITLE
AutoCloseable not implemented

### ISSUE THREAD

**Issue by ibiBgOR** [j256/ormlite-core#43]
It's the first time I work with ormlite. As I found on your site (http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_2.html#Using) it is a good pattern to close a connection in the finally block. 
I thought it would be pretty nice if the (e.g.) CloseableWrappedIterable implement the AutoClosable, so that the use of Java's try-with would be possible.

**Comment by j256** [comment]
AutoCloseable is in Java 7 only but I've already made the changes to have it be Closeable.  This has already been completed in trunk and will be in 4.49 which we are [finally] going to release within a week or 2.  See:  https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/dao/CloseableWrappedIterable.java
