### ISSUE TITLE
foreignAutoCreate is ignored on update

### ISSUE THREAD

**Issue by igromanru** [j256/ormlite-core#5]
The aforementioned parameter is ignored on update of the parent object. The instance of related class is only created, if the parent object also created, but not updated.

The probably solution is to extract the whole part (the complete if, responsible for this parameter) from MappedCreate.insert(), put it as protected method into the BaseMappedStatement class and call this method from the MappedUpdate.update() also.

**Comment by j256** [comment]
I've added more tests here and can't reproduce this.  Feel free to tweak the test and reopen if there is a problem.  See: https://github.com/j256/ormlite-core/commit/2768dc45a9561d75b9a2f40ce11fcf3ab96bd14a

**Comment by j256** [comment]
One extra comment is that you _must_ insert the answer into the database _before_ it is added to the question because otherwise there is no answer.id to be put into the the question.  I think that might have been the problem with your test.

**Comment by igromanru** [comment]
Thank you for your effort, but I can't remember any more. :D  
I am since years in another department and have no access to the code anymore.
