### ISSUE TITLE
generic inheritance error

### ISSUE THREAD

**Issue by adrianpop1990** [j256/ormlite-core#50]
I use ormlite-android 4.48 + ormlite-core 4.48 and get the following exception:
`java.sql.SQLException: queryForOne from database failed: SELECT * FROM ``basemodel`` WHERE ``_id`` = ?`
Is seems that `BaseParentRelationModel<P extends BaseModel>` can't be resolved.

##### E = CategoryModel
    List<E> _ItemList = null;
        try {
            QueryBuilder<E, Integer> _QueryBuilder = this.dao.queryBuilder();
            _QueryBuilder.orderBy(this.sortColumn, true);

            PreparedQuery<E> _PreparedQuery = _QueryBuilder.prepare();
            _ItemList = this.dao.query(_PreparedQuery);
        } catch (SQLException e) {
            Log.e(this.getClass().getName(), "" + e.getMessage());
        }

## model class:
```java
    @DatabaseTable(tableName = CategoryModel.TABLENAME)
    public class CategoryModel extends BaseParentRelationModel<CategoryModel> {
    ...
    }
```

## inheritance class 1:
```java
    public abstract class BaseParentRelationModel<P extends BaseModel> extends BaseModel {
    @DatabaseField(columnName = COLUMN_PARENT, canBeNull = true,
            foreignColumnName = P.COLUMN_ID, foreign = true, foreignAutoRefresh = true, foreignAutoCreate = true,
            maxForeignAutoRefreshLevel = 3)
    public P parent;
    public static final String COLUMN_PARENT = "parent_id";
    }
```

## inheritance class 2:
```java
    public abstract class BaseModel {
    @DatabaseField(columnName = COLUMN_ID, generatedId = true)
    public long id;
    public static final String COLUMN_ID = "_id";
    ...
    }
```

**Comment by adrianpop1990** [comment]
Hey, could you reproduce it already and when it will be fixed?
Best regards
Adrian

**Comment by j256** [comment]
Sorry for the delay on this.  I'm not sure there is a fix.  Because of [type erasure](https://docs.oracle.com/javase/tutorial/java/generics/erasure.html) ORMLite does not know the type of P at runtime so can't figure out which table contains the parent.

Not sure what the proper solution would be.  Sorry.
