### ISSUE TITLE
Provide parametrized filter method

### ISSUE THREAD

**Issue by p91paul** [j256/ormlite-core#55]
Look at those 2 methods I wrote in my application (getQuery and getRelationsQuery returns a QueryBuilder instance):

    public List<Document> getRelatedDocuments(Document document) throws SQLException {
        return this.getQuery().where().in("id", getRelationsQuery(document)).query();
    }

    public List<Document> getUnrelatedDocuments(Document document) throws SQLException {
        return this.getQuery().where().notIn("id", getRelationsQuery(document)).query();
    }

You see that they are almost equal, apart from the "in" vs "notIn". I would like to refactor them to a single method, and since I can't pass a method as a parameter, a method with a signature similar to `clause(ClauseType type, String columnName, Object value)` would be really appreciated, so that I can write

    public List<Document> getRelatedDocuments(Document document) throws SQLException {
        return getDocuments(ClauseType.IN, document);
    }

    public List<Document> getUnrelatedDocuments(Document document) throws SQLException {
        return getDocuments(ClauseType.NOT_IN, document);
    }

    public List<Document> getDocuments(ClauseType type, Document document) throws SQLException {
        return this.getQuery().where().clause(type, "id", getRelationsQuery(document)).query();
    }

Greatly reducing code duplication.

Of course I have an example for in/notIn, but same reasoning could be applied to eq, lt, le.... 

It makes perfect sense to keep current methods which are more straightforward to use, but adding a more generic one in some situations could be very handy.

**Comment by j256** [comment]
Thanks for this.  I understand the need but it would take a descent amount of refactoring inside of ORMLite that I'm just not willing to do.  Even though `IN` and `NOT IN` seem like simple operators, they are handled differently internally with some large switch statement.  I think right now I'd rather you write that code externally.  And `IN` is different than `lt`, etc. so they would use different parameters.

As an aside you can use `Where.rawComparison(columnName, SimpleComparison.*, value)`.
