### ISSUE TITLE
Support for primary keys that aren't INTs

### ISSUE THREAD

**Issue by noordawod** [j256/ormlite-core#59]
Hi again.
I have set up most of my tables to include a primary key which is BINARY(8). This allows for a 16^16 possible rows, which is adequate for me.
OrmLite's (id=true) doesn't play well with this as it expects the field to be an integer.
Is there plans to support this functionality? Or maybe it's already supported?
Thanks in advance.

**Comment by j256** [comment]
Does your merge that allows BigInteger ids resolve this?

**Comment by noordawod** [comment]
Yes, but I believe you didn't merge that part in, @j256.
Should I send a pull request for that?

**Comment by j256** [comment]
I did merge in the pull request that allows BigIntegers to be primary keys.  Isn't that what you are talking about?  Or are you talking about `byte[]` being primary keys.  I actually did end up allowing this.  Just added this test to prove it.  See: https://github.com/j256/ormlite-core/commit/1184b6597b1ad73c4a1a3b0016b1bb176d789e00

**Comment by noordawod** [comment]
Fabulous, then all is good!
