### ISSUE TITLE
Dynamic table name.

### ISSUE THREAD

**Issue by noordawod** [j256/ormlite-core#63]
I'm facing this requirement when doing sharding of tables:

I currently cannot set the table name dynamically, and it has to be set using a static annotation. For most times, this is alright, but I need this to be set dynamically.

Got an idea how to do this with the current implementation?

**Comment by j256** [comment]
You can certainly set the table name dynamically with the DatabaseTableConfig configuration stuff.  You can create it programmatically or generate them from the class and then tune it.

You may also want to consider implementing your one ConnectionSource.  Hrm.  What would be useful there is for ORMLite to ask the ConnectionSource for a connection to a particular database, even if this argument is ignored with all current implementations.

**Comment by noordawod** [comment]
I like the solution with ConnectionSource, it gives the app the ultimate power on selecting the best source of a data store. However, I'm not sure where to start or whether there's a need at all to send a pull request to make this a reality.

If you got few moments to direct me on how to approach this, it would be great. Thanks in advance!

**Comment by j256** [comment]
Just checked this in.  See: https://github.com/j256/ormlite-core/commit/869ce252e49d74678e3abf0b8c6536d528c4083a

**Comment by noordawod** [comment]
Beautiful @j256!! Thank you :)
