### ISSUE TITLE
Microseconds are not supported by SimpleDateFormat

### ISSUE THREAD

**Issue by fkaelberer** [j256/ormlite-core#65]
```		
String format = "yyyy-MM-dd HH:mm:ss.SSSSSS";
DateFormat dateFormat = new SimpleDateFormat(format);
```
The default date format at [BaseDateType.java#L20](https://github.com/j256/ormlite-core/blob/17b98fbb49b0e8f94b8073ab6fa0dc335f039ad4/src/main/java/com/j256/ormlite/field/types/BaseDateType.java#L20) contains six digits after the decimal point.
However, as 'S' stands for miliseconds (which max out at 999), the first 3 digits after the decimal point are always 0.
For example, 1.567 seconds are printed as 
`00:00:01.000567` and not as `00:00:01.567` or `00:00:01.567000` as one would expect.

**Comment by j256** [comment]
Please see the release notes in the 4.45 version.  This was a big headache and I had to roll it back.  You can specify a custom date format:  http://ormlite.com/docs/4.45
