### ISSUE TITLE
UniqueCombo and DAO

### ISSUE THREAD

**Issue by carmas123** [j256/ormlite-core#66]
Hi, I've a table with 3 column as primarykey and I've set the class like this:

```
public class myTab {

    @DatabaseField(uniqueCombo = true, uniqueIndexName = "PK_Primary", width = 3)
    public String myField1;
    @DatabaseField(uniqueCombo = true, uniqueIndexName = "PK_Primary", width = 3)
    public String myField2;
    @DatabaseField(uniqueCombo = true, uniqueIndexName = "PK_Primary")
    public int myIntField;
    @DatabaseField(width = 8)
    public String myValueNoKey;
```

but now I don't know how can I make a DAO for this class...

```
Dao<myTab, ?? AND HERE ??> dao
```

many thanks...

**Comment by j256** [comment]
If there is not a single key then you could make it `Void` which is basically a `null` class.  It means that you can't get by id or anything but you can certainly use equals on your 3 fields.

**Comment by j256** [comment]
I'm going to mark this as closed even though it's not the best solution.  Feel free to reopen if you need more help.
