### ISSUE TITLE
patch: support custom db objects (example: h2 spatial geometry and point)

### ISSUE THREAD

**Issue by rzorzorzo** [j256/ormlite-core#68]
hello,

i needed support for database specific return objects such as Point in H2.
i see that others had the same issue:

https://stackoverflow.com/questions/12220234/model-geometry-point-with-ormlite
https://stackoverflow.com/questions/14751386/using-postgis-with-ormlite

attached is a patch for using custom db objects and data types.

Here is a usage example:

the model:

@DatabaseTable(tableName = "LOCATIONS")
public class Location
{
	static final GeometryFactory geometryFactory = new GeometryFactory();
	
	@DatabaseField(index=true)
	String _name = "";
	@DatabaseField(persisterClass = PointType.class)
	Point _gps = geometryFactory.createPoint(new Coordinate(0, 0));
}

mapping of point type:

public class PointType extends BaseDataType
{
	private static final PointType singleTon = new PointType();

	public static PointType getSingleton() {
		return singleTon;
	}

	private PointType() {
		super(SqlType.OTHER);
	}
	
	public String getSqlOtherType()
	{
		return "GEOMETRY";
	}
	

	/**
	 * Here for others to subclass.
	 */
	protected PointType(SqlType sqlType, Class<?>[] classes) {
		super(sqlType, classes);
	}

	@Override
	public Object parseDefaultString(FieldType fieldType, String defaultStr) throws SQLException {
		throw new SQLException("Default values for point types are not supported");
	}

	@Override
	public Object resultToSqlArg(FieldType fieldType, DatabaseResults results, int columnPos) throws SQLException {
		return results.getObject(columnPos);
	}

	@Override
	public Object javaToSqlArg(FieldType fieldType, Object obj) throws SQLException {
		return obj;
	}

	@Override
	public boolean isValidForField(Field field) {
		return true;
	}

	@Override
	public boolean isComparable() {
		return false;
	}

	@Override
	public boolean isAppropriateId() {
		return false;
	}
}

create a spatial index:

		locationDao
				.executeRaw("CREATE SPATIAL INDEX IF NOT EXISTS LOCATIONS_SPATIALINDEX ON LOCATIONS(_GPS)");

search for locations in the vicinity

[Uploading ormlite2.diff.txt…]()
[ormlite2.txt](https://github.com/j256/ormlite-core/files/41047/ormlite2.txt)

 of a gps coordinate:

	    QueryBuilder<Location, Long> lqb = locationDao.getLocationDao()).queryBuilder();

		double[][] polygon = GeoUtils.polygone(lon, lat, km);
		StringBuffer b = new StringBuffer("_GPS && 'POLYGON ((");
		for (int i=0; i<5; i++)
		{
			b.append(polygon[i][0]);
			b.append(" ");
			b.append(polygon[i][1]);
			if (i != 4)
				b.append(",");
		}
		b.append("))'");
	    
	    lqb.where().raw(b.toString()).query()

[ormlite1.txt](https://github.com/j256/ormlite-core/files/41046/ormlite1.txt)
[Uploading ormlite2.txt…]()

**Comment by rzorzorzo** [comment]
[ormlite2.txt](https://github.com/j256/ormlite-core/files/41048/ormlite2.txt)

**Comment by j256** [comment]
This seemed pretty easy and useful so I hand merged it.  See: https://github.com/j256/ormlite-core/commit/4d08d8760de30c96feaddc243279beaa65fd9178
