### ISSUE TITLE
Feature request: auto upgrade schema

### ISSUE THREAD

**Issue by molexx** [j256/ormlite-core#70]
Keeping track of changes to classes, maintaining a version number and writing manual 'scripts' in onUpgrade() is error-prone and becomes unwieldy as the number of releases grows.

OrmLite could automate this to varying extents. Initially for add/remove columns, and probably also for changing data type or size where the data is compatible.

An initial implementation could compare the 'create table' statement generated from the Class with the current database table structure and if there is any mismatch: rename the table, create a new table, copy all the data across, then delete the old renamed table.

Later enhancements could analyse the mismatches and generate 'alter table' statements for faster operation but the above might be acceptable for many applications in the meantime.

**Comment by kpgalligan** [comment]
This is one of those things that seems easy but is rough and has unintended
consequences.  Assuming you're talking Android, also, you can't really
change column types, nor remove them.

So, you could look for columns that don't exist and add them.  If you ever
needed to "port" data, though, with an update statement, this will get
really tricky if a user is updating through multiple versions, and you'll
need to test all of that.

Most other production db orm systems rely on sql to do updates to schema.
Just one of those things.

On Fri, Jan 22, 2016 at 4:16 PM, molexx <notifications@github.com> wrote:

> Keeping track of changes to classes, maintaining a version number and
> writing manual 'scripts' in onUpgrade() is error-prone and becomes unwieldy
> as the number of releases grows
>
> OrmLite could automate this to varying extents Initially for add/remove
> columns, and probably also for changing data type or size where the data is
> compatible
>
> An initial implementation could compare the 'create table' statement
> generated from the Class with the current database table structure and if
> there is any mismatch: rename the table, create a new table, copy all the
> data across, then delete the old renamed table
>
> Later enhancements could analyse the mismatches and generate 'alter table'
> statements for faster operation but the above might be acceptable for many
> applications in the meantime
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j256/ormlite-core/issues/70>.
>



-- 
Kevin Galligan
http://about.me/kpgalligan

Share the Motorhead:
https://www.youtube.com/playlist?list=PL0mtSKSOY5MtzRWJnJh3FAVBR9ynCMe2W

**Comment by molexx** [comment]
Thanks for the response. What do you think about recreating the table then copying the data? As you say that will only work as long as the data formats haven't changed too much but it would be useful for a lot of cases. 

The docs would have to point out the restrictions.

I'd raise performance as a concern but as you say when some DDL isn't supported a recreate is the only way.

**Comment by kpgalligan** [comment]
I wouldn't generally recommend it.  Managing versions can be tedious, but
auto-modifying tables is very problematic. Much more so than the code
trying to figure out your intention with adding/removing a column.  Some
cases are simple, but many will get apps into trouble.  You can try it.  I
might be overly pessimistic, but guessing it wouldn't be used much.
Possibly more during development, but I just drop and recreate everything
on an upgrade during dev (generally).

You'll also need to be careful with foreign references, autogen ids, and
make sure transactions in sqlite can roll back ddl changes, including table
drops, which I don't know off hand.  Its one thing if your app crashes but
your data is intact.  You can release another version.

I know this sounds like a dismissive answer, and I apologize about that,
but this is the quickest way I can explain my position without writing a
long paper and drawing charts.  As frustrating as DDL and version numbers
seem, automatically modifying table schemas isn't a new idea, and we still
have version numbers and DDL for a reason.  But its open source, so, you
know.

On Fri, Jan 22, 2016 at 5:02 PM, molexx <notifications@github.com> wrote:

> Thanks for the response. What do you think about recreating the table then
> copying the data? As you say that will only work as long as the data
> formats haven't changed too much but it would be useful for a lot of cases.
>
> The docs would have to point out the restrictions.
>
> I'd raise performance as a concern but as you say when some DDL isn't
> supported a recreate is the only way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/j256/ormlite-core/issues/70#issuecomment-174067159>.
>



-- 
Kevin Galligan
http://about.me/kpgalligan

Share the Motorhead:
https://www.youtube.com/playlist?list=PL0mtSKSOY5MtzRWJnJh3FAVBR9ynCMe2W

**Comment by molexx** [comment]
Thanks again for your reply and explanation.

Trying to alter a table is out, and trying to do anything automatically is out.

Do you see any merit in a method such as `recreateTableAndMigrateData()` for developers to call explicitly? This would perform the rename/create new table/copy data/drop procedure I mentioned above (no altering of tables, no guessing what might have changed) and look after the references, indexes, and autogen ids. I wouldn't expect this to be rollback-able but it would be able to undo itself should it encounter any errors as the original table is not dropped until the end.

This would be useful when versioned DDL scripting is being done but the DDL isn't available on the platform - such as drop column. In that case developers would have to perform this procedure.

It could be accompanied by a method such as `checkTableDefinitionMatch()` which would compare the existing database table's definition vs the definition OrmLite would use if it were to create the table from the current class. This would allow developers to do a sanity check at a time of their choosing rather than trying to parse an SQLException thrown from dao usage in the application.

**Comment by j256** [comment]
I'm going to close this.  Feel free to reopen with maybe a merge into -android with some code that would help with this.

**Comment by molexx** [comment]
I have been testing a static method 'recreateTableAndMigrateData()' which renames a table, recreates the table from the updated class using TableUtils.createTable(), then copies over the data for columns that have the same name. It's needed when I need to drop a column and I've been (admittedly lazily) using it when adding columns rather than tracking each column add individually across app build versions.
It won't handle changed column names or data formats and doesn't attempt to move over any indexes or constraints, but I would be happy to PR this if it would be useful?

**Comment by ChristopheCVB** [comment]
Hi @molexx ! Do you still have the code you're talking about ? I'm really interested in taking a look at it.

**Comment by molexx** [comment]
Sure: https://gist.github.com/molexx/19d09387d9cae3b99ad8cef3de6a2f38


I manually call this from a series of oldVersion checks in `onUpgrade()`, e.g.:
```
    if (oldVersion < 8) {
        OrmLiteUpgradeTable.migrateTable(connectionSource, TableA.class);
    }
```
