### ISSUE TITLE
Log more when a field is not found

### ISSUE THREAD

**Issue by stephanenicolas** [j256/ormlite-core#71]
we got this crash on Crittercism pretty often : 

```bash
Caused by: java.sql.SQLException: Could not find declared field with name 'modificationDate' for class xxx.WidgetSummary
114	at com.j256.ormlite.table.DatabaseTableConfig.convertFieldConfigs(DatabaseTableConfig.java:242)
115	at com.j256.ormlite.table.DatabaseTableConfig.extractFieldTypes(DatabaseTableConfig.java:101)
116	at com.j256.ormlite.dao.BaseDaoImpl.initialize(BaseDaoImpl.java:151)
117	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:126)
118	at com.j256.ormlite.dao.BaseDaoImpl.<init>(BaseDaoImpl.java:117)
119	
```

We have proguarded the field, it is found 99.999% of the time, but we some time have crashes like this one. The rate is approximately 1 for 100 million launches. Pretty low, not related to a specific device. 

Would it be possible to log all the fields in this case, so that we can understand what happens to them.

**Comment by j256** [comment]
Wow.  No idea what would be causing that.  Is it possible that it is some sort of race condition?

In terms of logging, you are certainly welcome to add logging to the source.  Maybe branch and create your own version?  Or maybe I'm not understanding the question?

**Comment by stephanenicolas** [comment]
We would just appreciate to get all the fields that can be found by reflection listed if that's possible. Or even better, compare it with the fields listed in the config.

We are really not sure about what happens. I think as well it might be a race condition between upgrade and app run.

**Comment by j256** [comment]
You can interrogate the DAO by calling: http://ormlite.com/javadoc/ormlite-core/com/j256/ormlite/dao/BaseDaoImpl.html#getTableInfo() (assuming your DAO is a BaseDaoImpl) which gets you all of the fields.  Does that help @stephanenicolas ?

**Comment by j256** [comment]
How about doing your own reflection on the class first off. MyClass.class.getDeclaredFields()?

**Comment by stephanenicolas** [comment]
we can log that for sure and cross fingers that the bug happens on the same DAO, we got 50 of them...
Having it inside the source code of ormlite would for sure help to catch what happens, and we would prefer to not to use a fork..

**Comment by j256** [comment]
I'm not sure how ORMLite can help here.  Feel free to reopen if you have specific ideas.
