### ISSUE TITLE
Invalid package reference in library ormlite-core-4.49-SNAPSHOT.jar

### ISSUE THREAD

**Issue by Nescafemix** [j256/ormlite-core#73]
Lint is showing me an error trying to build the apk in Android:

    InvalidPackage: Package not included in Android
    ../../libs/ormlite-core-4.49-SNAPSHOT.jar: Invalid package reference in library; 
    not included in Android:     javax.persistence. 
    Referenced from com.j256.ormlite.misc.JavaxPersistenceImpl.

**Comment by j256** [comment]
You need both the -android and -core libraries.  Please RTFM.

**Comment by Nescafemix** [comment]
Hi. 
I had already read the fucking manual and yes, I was using both of them...
My solution was to add an option to ignore the lint error in the lint.xml file.

```
<issue id="InvalidPackage">
        <ignore regexp="ormlite-core-4.49" />
</issue>
```

**Comment by j256** [comment]
So lint wasn't listening to maven or your deps?  That's unfortunate.  Glad you figured it out.

**Comment by kenyee** [comment]
FWIW, I also had to do this w/ ormlite 5.0 and also have -core and -android specified in my gradle file.  I think it's a bug in Android's lint.  I added
 <ignore regexp="ormlite-core-*" />
so I wouldn't have to worry about version upgrades causing false positives in lint :-)
