### ISSUE TITLE
4.50?

### ISSUE THREAD

**Issue by lostmsu** [j256/ormlite-core#74]
There were no releases since 2013. Are there any plans on continuing support?

**Comment by ened** [comment]
@j256 Do you have a snapshot maven repo for others to try? I have a direct use case with the `DaoObserver` classes and would love to bring that in. :)

**Comment by j256** [comment]
Yeah, well I guess you could tell by my answer how often I do releases.  The Android side of the fence has really frozen me in place.  Painful.  In github you can do your own branching anytime @ened .

**Comment by ened** [comment]
@j256 How can the community help you?

**Comment by j256** [comment]
Sorry for the delay.  The community can help, I guess by helping @kpgalligan or finding someone to take over the Android side of the fence.  I can handle the Java side and I'm happy to be the anchor for ormlite-core and -jdbc but I'm out of my league on the android side.

**Comment by sic2** [comment]
@j256 are you planning to push a newer SNAPSHOT on the Maven repository? 
It would be useful to have the latest changes there. 

Thanks!

**Comment by j256** [comment]
Just pushed 5.0 to the repo and release dirs.  Fire in the hole.
