### ISSUE TITLE
Why enum use java.lang.Enum.name() instead of use toString().

### ISSUE THREAD

**Issue by jiajia-li** [j256/ormlite-core#75]
Some time we want to use toString instead of java.lang.Enum.name() .How about support both of it.

**Comment by j256** [comment]
Hrm.  So this is so you can override the `toString()` for the enum?

**Comment by j256** [comment]
I could certainly support both but what about name clashes.  How would I resolve them?  How about a EnumToStringType (differetn from EnumStringType).  That would use toString() instead of name().

**Comment by j256** [comment]
See https://github.com/j256/ormlite-core/commit/75bd40c0e74e26d58e4c0c1307022177d053d806
