### ISSUE TITLE
Bug with cache and select columns

### ISSUE THREAD

**Issue by pimduin** [j256/ormlite-core#78]
The mapRow method in the BaseMappedQuery class disregards the results when the resulting database object can be found in the object cache.

See BaseMappedQuery line 41-49.

I ran into this problem because I wanted to do a partial refresh of a database object. Instead of retrieving the object from cache and update the object with the values from the query result, it just returns the object from cache. 
Not sure if this is intended behavior.

I wrote a test method to demonstrate the problem:
https://gist.github.com/pimduin/61d0a093a1e209b8995858ac7177a6e0

**Comment by j256** [comment]
Good one.  Thanks much for the test.  So easy to find the problem with it.  I've replicated in trunk.  Working on it now.

**Comment by j256** [comment]
Ok.  This has finally been fixed.  Bit tricky but easy to reproduce.  Thanks.   https://github.com/j256/ormlite-core/commit/40e14866dcc377f7aa5654c609c42946ef20c8ab
