### ISSUE TITLE
Refactoring model packages not updating DatabaseTableConfig

### ISSUE THREAD

**Issue by josephmbeveridge** [j256/ormlite-core#79]
Hey,

I'm in the process of refactoring our model class package hierarchy and running into issues when upgrading to this new refactored version. It appears that `DatabaseTableConfig` stores the expected path to a given class, to be used when deserializing from the db. However, it doesn't appear to be updated after upgrades, at least not in my case.

My specific case is moving a class from `com.company.services.path.Class` to `com.company.sdk.services.path.Class`

Is there a way to trigger a recreation of this table? Ideally I would like to avoid having to manually modify the table. I haven't been able to find any good sources on how to do this.

**Comment by j256** [comment]
Can you please open this issue in ormlite-android issue: https://github.com/j256/ormlite-android/issues
