### ISSUE TITLE
error appears while trying to remove iter

### ISSUE THREAD

**Issue by GitHubMurt** [j256/ormlite-core#80]
To the point.

I'm using thie library in Android. I have following structure

```
class Project{
...
    @SerializedName("attributes")
    @Expose
    @ForeignCollectionField(eager = true)
    private Collection<Attribute> AttributesDB = new ArrayList<>();
...
}
```

I store project in singleton in order to avoid unecessary calls to DB while traversing through my Application.
In some point I have to delete explicitly only one element from this collection.
Firstly I issue call to Database

```
...
dbHelper.getAttributeDao().delete(attribute)
...
```

Later is removal succeed I want to remove record from singleton.
I identify certain attribute by comapring its idDB.

```
public void removeFromProject(Attribute attribute){
  Iterator<Attribute> iter = projec.getAttributes().iterator();
              while (iter.hasNext()){
                  if(iter.next().getIdDB() == rta.getIdDB()) {
                      iter.remove();
                      Log.i("Attribute", "attribute removed from project");
                  }
              }
}
```

But _iter.remove()_ causes **IllegalStateException**, any way if I do

```
public void removeFromProject(Attribute attribute){
try{
  Iterator<Attribute> iter = projec.getAttributes().iterator();
              while (iter.hasNext()){
                  if(iter.next().getIdDB() == rta.getIdDB()) {
                      iter.remove();
                      Log.i("Attribute", "attribute removed from project");
                  }
              }
}catch(IllegalStateException e){
      Log.e("Remove Attribute", "exception raised")
}
}
```

item is removed successfully. Event if I will not delete attribute earlier using _dao.delte(attribute)_
it will throw exception. I raport It because in fact iterator is removing this _attribute_ but It throws exception

**Comment by j256** [comment]
I don't quite understand.  Are you trying to remove it twice?

**Comment by j256** [comment]
So the `Collection` doesn't really _store_ the attributes.  It is more like a view into the `Attributes` table of the attributes associated with a particular `Project`.  So all you should need to do is to remove it from the `Attributes` table.  If you have outstanding `Project` instances then they will need to be refreshed.  You can also remove it from the `Collection` and _not_ to the `dao.delete(...)`.
