### ISSUE TITLE
Add title to the LICENSE file

### ISSUE THREAD

**Issue by waldyrious** [j256/ormlite-core#82]
It appears to be the ISC license, but that isn't obvious unless the text is compared to a reference. The boilerplate in http://choosealicense.com/licenses/isc/ provides an example.

**Comment by j256** [comment]
I can add the title but why does the title matter?  Isn't it the content that matters and should be compared?

**Comment by j256** [comment]
This has been done.

**Comment by waldyrious** [comment]
Thank you. There are various reasons to add the title. One is to make it clearer what license is actually being used (e.g. to quickly verify whether a project's license is among those vetted by the relevant FOSS organizations). It also improves searching (especially since licenses often use very similar language). Additionally, this can serve as a fast early check for content-based license matchers. And I'm sure there are other reasons I'm missing.

**Comment by j256** [comment]
Good points.
