### ISSUE TITLE
DataType parameter in DatabaseFieldConfig constructor is ignored

### ISSUE THREAD

**Issue by magicgoose** [j256/ormlite-core#83]
https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/field/DatabaseFieldConfig.java#L94

https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/field/DatabaseFieldConfig.java#L101

Looks like an error. I'm wondering what are practical implications of this.

**Comment by j256** [comment]
Uh wow.  The only place this is used is in tests unless people are constructing them directly.   Fixed.  See https://github.com/j256/ormlite-core/commit/9228a57b190d4d2ad128d581f99dd6344ae10db3
