### ISSUE TITLE
Getting database name (Catalog) for a ConnectionSource

### ISSUE THREAD

**Issue by noordawod** [j256/ormlite-core#84]
Not an issue per se, but how do you get the catalog (database) name a ConnectionSource is connected to? It's not the database type ("MySQL", "Oracle", etc.) that `getDatabaseName()` seems to return, which imho should be renamed to `getDatabaseType()`.

Alternatively, add a `getCatalogName()` to return the name of the connected database.

**Comment by j256** [comment]
I'm confused. `ConnectionSource.getDatabaseType()` has existed for a while.

**Comment by j256** [comment]
Also I'm confused. `ConnectionSource.getDatabaseType()` has existed for a while.

**Comment by noordawod** [comment]
It was only a side note, @j256, so I wouldn't stress too much about the `getDatabaseType()` method. My initial question was to the possibility of getting the catalog name for a `ConnectionSource`. For MySQL, as an example, issuing a simple `SELECT DATABASE()` would give back the answer.

I don't know about other database servers, but I would assume it's such a trivial thing...

Anyway, worth implementing?

**Comment by j256** [comment]
The issue is that a `ConnectionSource` can connect to a number of different databases so there isn't just one.  I'd recommend that you use the raw query stuff in the `Dao` to get the databases on the server you are connecting to.   Reopen if you think otherwise.
