### ISSUE TITLE
TransactionManager.callInTransaction is not thread safe

### ISSUE THREAD

**Issue by snakelizzard** [j256/ormlite-core#85]
Doing `TransactionManager.callInTransaction` on same connection source in different threads can result in invalid auto commit state. Each operation handles this flag not taking into account that it can be changed in different thread.

**Comment by j256** [comment]
Is this with a single connection `ConnectionSource` or a multi?  If it is a single then this makes sense because it is using the same connection in different threads.  That's not a good idea @snakelizzard.

**Comment by snakelizzard** [comment]
Took a deep look on connection anatomy for various databases, and, yes, I agree, it was a bad idea to use shared write connection for several threads.
