### ISSUE TITLE
ORMLite compatibility with Oracle 11 (LONG String)

### ISSUE THREAD

**Issue by benedekh** [j256/ormlite-core#86]
Dear All,

I have a table which has a String field. The field's (preferred) data type is LONG_STRING, because it may contain more than 256 characters. When I use PostgreSQL DB as a backend, it translates into the corresponding data type in the DB without any problems. However, when I use Oracle (Oracle DB 11) as the backend it has some problems.

First, it creates a field typed LONG in the database which has been deprecated since Oracle DB v8 as far as I know. 

Second, in the INSERT_INTO statement a TO_LOB(field_name) may not be called, so that the field is not serializable into the DB. The error message says: "expected CHAR received LONG".

May anyone have a suggestion, how to solve this problem?

Thank you for the kind help in advance.

Cheers,
Ben

**Comment by j256** [comment]
Very only question so you've prolly moved on.  For posterity, you can override the `OracleDatabaseType` in the OrmliteJdbc package and look at `appendLongStringType()` method and maybe others.

**Comment by benedekh** [comment]
I will close this issue for now as I'm short on time with investigating it further and making any contributions.

However, thank you @j256 for the feedback!
