### ISSUE TITLE
Crash on  QueryBuilder.orderBy() when changing device language to Turkish

### ISSUE THREAD

**Issue by cezarvancea** [j256/ormlite-core#87]
Hi @j256 

I'm currently using ormlite-core 5.0 and getting a crash on QueryBuilder.orderBy(). My order by column is not being recognized when the language of the device is being set to Turkish.

Here's part of the stack trace:

`java.lang.IllegalArgumentException: You should use columnName 'providedId' for table trip instead of fieldName 'providedId'
                                                                                           at com.j256.ormlite.table.TableInfo.getFieldTypeByColumnName(TableInfo.java:151)
                                                                                           at com.j256.ormlite.stmt.StatementBuilder.verifyColumnName(StatementBuilder.java:183)
                                                                                           at com.j256.ormlite.stmt.QueryBuilder.orderBy(QueryBuilder.java:176)
                                                                                           at com.mttnow.android.bcd.persistence.dao.TripDao.getQueryBuilder(TripDao.java:151)
                                                                                           at com.mttnow.android.bcd.persistence.dao.TripDao.queryForAllOrdered(TripDao.java:84)`

Related to https://github.com/j256/ormlite-core/issues/67

Thank you.

**Comment by j256** [comment]
Huh.  Fascinating.  Can you reproduce a unit test which demonstrates this?

**Comment by cezarvancea** [comment]
Hi @j256,
I've setup a private test project(which you can use to checkout the crash) that I can invite you to. Do you have an email address that I can send the invite to? 

Thanks.

**Comment by cezar-bestsoft** [comment]
Hi @j256 ,
Any update on this one?

**Comment by cezarvancea** [comment]
Hi @j256 ,
is there any update on this?

**Comment by j256** [comment]
Sorry for the delay on this.  Can you post a unit test for this?

**Comment by spelhan** [comment]
I have same problem, check [http://pastebin.com/Jxypz6d2]

**Comment by chihung93** [comment]
I have same problem when change local from English (after created database) to Chinese , italian , Vietnam vv
Related to #108

**Comment by chihung93** [comment]
Related to #108

**Comment by chihung93** [comment]
Why you don't use equalsIgnoreCase for compare fields ?

**Comment by chihung93** [comment]
with my issues :
I figured out a ingenious solution for my problem

```
public static final String FIELD_IS_LOCAL = "isLocal";
    @DatabaseField(columnName = FIELD_IS_LOCAL)
    private Boolean isLocal = true;
```

When queries :

```
public String getColumnNameWithLocale(String column){
        return getColumnNameWithLocale(column,Locale.ENGLISH);
    }

    public String getColumnNameWithLocale(String column, Locale locale){
        if (TextUtils.isEmpty(column)) return "";
        return column.toLowerCase(locale);
    }

builder.orderBy(getColumnNameWithLocale(Favorite.FIELD_ORDER),ascending).where()
                    .eq(getColumnNameWithLocale(Favorite.FIELD_IS_LOCAL)
```

**Comment by chihung93** [comment]
Fixed :

```
/**
	 * Return the {@link FieldType} associated with the columnName.
	 */
	public FieldType getFieldTypeByColumnName(String columnName) {
		if (fieldNameMap == null) {
			// build our alias map if we need it
			Map<String, FieldType> map = new HashMap<String, FieldType>();
			for (FieldType fieldType : fieldTypes) {
				map.put(lowerCaseEntityName(fieldType.getColumnName()), fieldType);
			}
			fieldNameMap = map;
		}
		FieldType fieldType = fieldNameMap.get(lowerCaseEntityName(columnName));
		// if column name is found, return it
		if (fieldType != null) {
			return fieldType;
		}
		// look to see if someone is using the field-name instead of column-name
		for (FieldType fieldType2 : fieldTypes) {
			if (fieldType2.getFieldName().equals(columnName)) {
				throw new IllegalArgumentException("You should use columnName '" + fieldType2.getColumnName()
						+ "' for table " + tableName + " instead of fieldName '" + fieldType2.getFieldName() + "'");
			}
		}
		throw new IllegalArgumentException("Unknown column name '" + columnName + "' in table " + tableName);
	}

private String lowerCaseEntityName(String columnName) {
		/*
 		 * We are forcing the ENGLISH locale because of locale capitalizaton issues. In a couple of languages, the
 		 * capital version of many letters is a letter that is incompatible with many SQL libraries. For example, in
 		 * Turkish (Locale.forLanguageTag("tr-TR")), "i".toUpperCase() returns "İ" which is a dotted uppercase i.
 		 */
		return columnName.toLowerCase(Locale.ENGLISH);
	}
```

**Comment by j256** [comment]
Merged recently.  Sorry for the delay.
