### ISSUE TITLE
limit does not work together with queryForFirst

### ISSUE THREAD

**Issue by helloworld1** [j256/ormlite-core#91]
The following code worked in 4.48. But now, it doesn't work 

```
  QueryBuilder<Card, Integer> qb = queryBuilder();
  PreparedQuery<Card> pq = qb.limit(1L).orderBy("ordinal", false).prepare();
  return queryForFirst(pq);
```

It generated the following sql:
SELECT \* FROM `cards` ORDER BY `ordinal` DESC LIMIT 1  LIMIT 1

**Comment by j256** [comment]
Right because queryForFirst puts in a limit.  But I can see that it should first see if a limit has been set and certainly not generate two of them.

**Comment by helloworld1** [comment]
I think ORMLite shouldn't generate illegal SQL statement for any platforms. For Android specific case, probably, additional check to remove the second limit statement would be necessary.

**Comment by j256** [comment]
Unfortunately I don't see an easy way to fix this.  The `LIMIT 1` is pretty much a hack anyway.  The query string has already been generated so I can't just drop the `LIMIT 1` if another limit statement is in the SQL and I don't want to go looking for LIMIT in case it is in a string or something.

Not the best solution but flagging for the user that they have both a limit and a first seems like the easy/best solution right now.
