### ISSUE TITLE
In BaseDaoImpl, getTableName() should come from tableInfo

### ISSUE THREAD

**Issue by saschoar** [j256/ormlite-core#94]
If a Dao has been constructed with an annotated model class, this results in a `NullPointerException`:
https://github.com/j256/ormlite-core/commit/869ce252e49d74678e3abf0b8c6536d528c4083a#diff-e3618befb795f3d589901ed6df2c8049R1028

...because `tableConfig` was never initialized.

A fix would be to get the table name from `tableInfo`:
`return tableInfo.getTableName();`

**Comment by 0xabadea** [comment]
Ran into this too and created https://github.com/j256/ormlite-core/pull/100.

**Comment by vyguera** [comment]
When will this fix be release?
