### ISSUE TITLE
Lazy ForeignCollectionField are loaded everytime I access them

### ISSUE THREAD

**Issue by LubomirKovalcik** [j256/ormlite-core#95]
This is more likely a feature more then bug.

However there is no way to load lazy ForeignCollectionField only once. You either load all at once with eager or load all when they are accessed everytime again and again with lazy collection. So lazy feature is only probably to save memory , but If I want to save cpu and not load it everytime it is accessed , because it was alread loaded before there is no way to do it?

**Comment by j256** [comment]
Yeah sorry but no.  Lazy is specifically a view to the database.  Behind the lazy connection could be a million results and I don't want to have ORMLite cache them inappropriately.  Maybe use an object cache?
