### ISSUE TITLE
unique and conflict with replace

### ISSUE THREAD

**Issue by flztsj** [j256/ormlite-core#97]
https://groups.google.com/forum/#!topic/ormlite-android/ASup7O_YaiY

like the url, do you have plan support it?

**Comment by flztsj** [comment]
@j256

**Comment by j256** [comment]
Which part?

**Comment by flztsj** [comment]
For the people who want to change all the 'unique=true' to add 'ON CONFLICT REPLACE' in SQLite after it, try this:

Change this in (com.j256.ormlite.db.BaseDatabaseType.java):
	private void addSingleUnique(StringBuilder sb, FieldType fieldType, List<String> additionalArgs,
			List<String> statementsAfter) {
		StringBuilder alterSb = new StringBuilder();
		alterSb.append(" UNIQUE (");
		appendEscapedEntityName(alterSb, fieldType.getColumnName());
		alterSb.append(")");
		additionalArgs.add(alterSb.toString());
	}
to:
	private void addSingleUnique(StringBuilder sb, FieldType fieldType, List<String> additionalArgs,
			List<String> statementsAfter) {
		StringBuilder alterSb = new StringBuilder();
		alterSb.append(" UNIQUE (");
		appendEscapedEntityName(alterSb, fieldType.getColumnName());
		alterSb.append(") ON CONFLICT REPLACE");
		additionalArgs.add(alterSb.toString());
	}

This will ensures that all the fields with the (DatabaseField) annotation 'unique=true' also implements 'ON CONFLICT REPLACE' in SQLite. This is a temporarily fix, it's of course better to wait for a DatabaseField annotation 'columnDefinitionBefore' or even better 'onConflict =' where you can insert after the '=': ROLLBACK, ABORT, FAIL, IGNORE or REPLACE

**Comment by flztsj** [comment]
This will ensures that all the fields with the (DatabaseField) annotation 'unique=true' also implements 'ON CONFLICT REPLACE' in SQLite. This is a temporarily fix, it's of course better to wait for a DatabaseField annotation 'columnDefinitionBefore' or even better 'onConflict =' where you can insert after the '=': ROLLBACK, ABORT, FAIL, IGNORE or REPLACE

**Comment by pavlus** [comment]
What is the status of this issue?

**Comment by j256** [comment]
Status is that I've not done anything with it unfortunately.  I just added a new @DatabaseField method called `fullColumnDefinition`.  See: https://github.com/j256/ormlite-core/commit/cf64086d88d2eb9414c6badd8baf6632a9e11048

**Comment by jdrotos** [comment]
I was able to create an sqlite multi-column unique constraint with `ON CONFLICT REPLACE` using the following code snippet on one of the columns in the unique constraint:

`@DatabaseField(columnName = "col1", columnDefinition = "VARCHAR , UNIQUE( `col1` , `col2` ) ON CONFLICT REPLACE ")`

Kind of nasty, but so it goes.
