### ISSUE TITLE
Specify a function to apply to column when creating unique index

### ISSUE THREAD

**Issue by Diederikjh** [j256/ormlite-core#98]
My database table has a uniqueness constraint over two columns. Currently I'm using the `@DatabaseField(uniqueIndexName="ix_tasks")`  annotation on the two columns, and this works fine.  

Now the requirement has been refined slightly to have one of the columns (a username) be unique case insensitively.   As far as I can tell this can be achieved by creating the index with raw SQL:  `CREATE UNIQUE INDEX ix_tasks ON task ( createDate, lower(username) )` notice the `lower` function applied on the `username` column.  

How about a new annotation called `indexFunction`?  For my case I could then specify: 
```
class Task {
    @DatabaseField(uniqueIndexName="ix_tasks", indexFunction="lower")
    private String username;
...
}
```

Reading the [docs](http://ormlite.com/javadoc/ormlite-core/doc-files/ormlite_2.html#Local-Annotations) again, and thinking some more: specifying the column during table create with `CREATE TABLE task ( ..., username VARCHAR collate nocase , ...`  and then specifying the index normally works as well.  Looks like the index honours the collate for the column in question.

Hope this helps someone with a similar requirement.

**Comment by j256** [comment]
In this case I think you need to use the `@DatabaseField(columnDefinition = "VARCHAR collate nocase")`.  I don't see any easy way to do this otherwise that is supported by most database types.
