### ISSUE TITLE
SelectIterator: current() may be wrong.

### ISSUE THREAD

**Issue by renaudcerrato** [j256/ormlite-core#99]
Found an annoying bug when using `getRawResults()` to skip some rows:

![image](https://cloud.githubusercontent.com/assets/1930949/21145557/b93cb926-c11c-11e6-83ff-f3bd78036330.png)

The output is clear:

```bash
java.lang.AssertionError:
Expected: is <Bill Clinton>
but: was <John Fitzgerald Kennedy>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
at com.foo.sqlitetest.TestBug.bug(TestBug.java:68)
...
```

After doing some digging, [the culprit was easy to spot](https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/stmt/SelectIterator.java#L141). As a temporary workaround, we had to call [`moveToNext()`](https://github.com/j256/ormlite-core/blob/master/src/main/java/com/j256/ormlite/stmt/SelectIterator.java#L279) first to clear that flag.

**Comment by j256** [comment]
Now THAT is a good error report.  Thanks much @renaudcerrato.  Looks like the problem is that `moveAbsolute(...)` isn't clearing that flag.

**Comment by renaudcerrato** [comment]
Sure, here it is:

[test.tar.gz](https://github.com/j256/ormlite-core/files/649590/test.tar.gz)

As an open source maintainer on my spare time, I'm always requesting for tests in case of bug report =)

**Comment by j256** [comment]
Oh I hear that!  Thanks again.

**Comment by j256** [comment]
Ended up adding a `moveAbsolute(...)` method to the `CloseableIterator`.  Not sure why it wasn't there earlier.  https://github.com/j256/ormlite-core/commit/ae9eb233d746d558ba6345b7a47edc97d5b8e872
